function [fitresult, gof] = createFitScat(aa, r)
%CREATEFIT(AA,R)
%  Create a fit.
%
%  Data for 'untitled fit 6' fit:
%      X Input: aa from X6
%      Y Output: r from y6
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Apr-2023 13:50:17


%% Fit: 'untitled fit 6'.
[xData, yData] = prepareCurveData( table2array(aa), table2array(r) );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 6' );
plot( fitresult,"-.");
hold on
p=plot(xData, yData, 'Diamond', 'MarkerEdgeColor',[0 0 0], 'MarkerFaceColor',[0.4940 0.1840 0.5560]);
p(1).MarkerSize = 10;

grid off


